from . import help
from . import start
from . import phones
from . import iphone_handler
from . import redmi
from . import poco_handler
from .import vivo_handler
from . import huawei_handler
from . import laptop_handler
from . import acer_handler
from . import hp_handler
from . import macbook_handler
from . import samsung_handler
from . import maishiy_textnika_handler
from . import muzlatgich_handler
from . import washing_machine_handler
from . import microvawe_handler
from . import gaz_plita_handler
from . import buy_item_handler
from . import echo
