from . import iphone
from . import smartphones
from . import redmi
from . import pocco
from . import vivo
from . import huawei
from . import laptops
from . import acer
from . import hp
from . import macbook
from . import samsung
from . import maishi_textnika
from . import muzlatgich
from . import washing_machine
from . import gaz_plita
